steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${SERVICE_NAME}:$SHORT_SHA', './ExePlore']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${SERVICE_NAME}']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${SERVICE_NAME}'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/${SERVICE_NAME}:$COMMIT_SHA'
  - '--region'
  - '${REGION}'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/${PROJECT_ID}/${SERVICE_NAME}:$COMMIT_SHA'