# Generated by Django 4.0.1 on 2022-02-28 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0004_badge_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('badges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.badge', verbose_name='Badges')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
                ('visits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.location', verbose_name='Visits')),
            ],
        ),
    ]
