# Generated by Django 4.0.1 on 2022-03-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
