# Generated by Django 4.0.1 on 2022-03-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_player_badges_alter_player_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='player',
            name='visits',
        ),
    ]
