# Generated by Django 4.0.1 on 2022-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_earned_badge_visit_remove_player_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='test',
            field=models.CharField(default='test', max_length=10, verbose_name='Test'),
        ),
    ]
