# Generated by Django 4.0.1 on 2022-03-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_earned_badge_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earned_badge',
            name='test',
        ),
        migrations.AlterField(
            model_name='earned_badge',
            name='badge_earned_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time earned'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time visited'),
        ),
    ]
