# Generated by Django 4.0.1 on 2022-03-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_earned_badge_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='test',
        ),
    ]
