# Generated by Django 4.0.1 on 2022-03-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_location_icon'),
        ('users', '0011_remove_player_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Earned_Badge',
            new_name='EarnedBadge',
        ),
    ]
