# Generated by Django 4.0.1 on 2022-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.FileField(null=True, upload_to='images/', verbose_name='icon for badge'),
        ),
    ]
