# Generated by Django 4.0.1 on 2022-03-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.FileField(null=True, upload_to='images/', verbose_name='icon for location'),
        ),
    ]
